version: "3"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ../pgdata:/var/lib/postgresql/data
    ports:
      - '5431:5432'

  redis:
    image: redis
    command: ['--requirepass "secret"']
    ports:
      - '6379:6379'