
version: "3"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres$$
      POSTGRES_USER: postgres
      POSTGRES_DB: db
    volumes:
      - ../pgdata:/var/lib/postgresql/data
    expose:
      - 5432

  redis:
    image: redis
    command: ['--requirepass "secre$$t"']
    expose:
      - 6379

  web:
    image: local/ts-node-postgres-auth
    depends_on:
      - postgres
      - redis
    expose:
      - 4000
    environment:
      - POSTGRES_PASSWORD=postgres
      - REDIS_SECRET=secre$$t
      - COOKIE_SECRET=secret$$
      - NODE_ENV=production
      - POSTGRES_DB=postgres

  nginx:
    image: nginx
    depends_on:
      - web
      - redis
      - postgres
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 4000:443